//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libCounchinn.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ModeloLibCouchin : DbContext
    {
        public ModeloLibCouchin()
            : base("name=ModeloLibCouchin")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIRECCION> DIRECCIONs { get; set; }
        public virtual DbSet<PERSONA> PERSONAs { get; set; }
        public virtual DbSet<PUBLICACION> PUBLICACIONs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TABLA> TABLAs { get; set; }
        public virtual DbSet<TABLA1> TABLAS1 { get; set; }
        public virtual DbSet<TIPO_HOSPEDAJE> TIPO_HOSPEDAJE { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<FOTO> FOTOS { get; set; }
    
        public virtual ObjectResult<SEL_LOGIN_Result> SEL_LOGIN(string nOMBRE_USUARIO, string cONTRASEÑA)
        {
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_LOGIN_Result>("SEL_LOGIN", nOMBRE_USUARIOParameter, cONTRASEÑAParameter);
        }
    
        public virtual int INS_CONTRIBUCIONES_USUARIO(Nullable<int> iD_USUARIO, string mONTO, Nullable<System.DateTime> fECHA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var mONTOParameter = mONTO != null ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_CONTRIBUCIONES_USUARIO", iD_USUARIOParameter, mONTOParameter, fECHAParameter);
        }
    
        public virtual int INS_TIPOHOSPEDAJE(string dESCRIPCION)
        {
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_TIPOHOSPEDAJE", dESCRIPCIONParameter);
        }
    
        public virtual ObjectResult<SEL_TIPOHOSPEDAJE_Result> SEL_TIPOHOSPEDAJE(Nullable<bool> pARAM)
        {
            var pARAMParameter = pARAM.HasValue ?
                new ObjectParameter("PARAM", pARAM) :
                new ObjectParameter("PARAM", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SEL_TIPOHOSPEDAJE_Result>("SEL_TIPOHOSPEDAJE", pARAMParameter);
        }
    
        public virtual int UPD_ACTUALIZAR_CONTRASENA(Nullable<int> iD_USUARIO, string cONTRASEÑA)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(int));
    
            var cONTRASEÑAParameter = cONTRASEÑA != null ?
                new ObjectParameter("CONTRASEÑA", cONTRASEÑA) :
                new ObjectParameter("CONTRASEÑA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPD_ACTUALIZAR_CONTRASENA", iD_USUARIOParameter, cONTRASEÑAParameter);
        }
    }
}
